name: Meu primeiro workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Primeiro job executado

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Segundo job executado
        
  last-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Ultimo job executado
