name: Test Workflow.yml
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3.3.0

      - name: Install NodeJS
        uses: actions/setup-node@v3.3.0
        with: 
          node-vesion: 18
      - name: Install dependencies
        run: npm ci
